use_frameworks!
platform :ios, '9.0'

target 'RegeributedTextView_Example' do
    pod 'RegeributedTextView', :path => '../'
    target 'RegeributedTextView_Tests' do
        inherit! :search_paths
        pod 'Quick'
        pod 'Nimble'
    end
end
